Fix: Null values being stripped out by structr
Yellitech/Structr pull request #6
Opened 2018-03-02 06:30 UTC by finalgriever

h1. Issue:
When Structr was processing a map definition, it would strip out keys that had been given null values. It is important that this doesn't happen, because sometimes we want to know that a key was sent with a null value, so that we know we want to save an edit to a property by setting it to null.

For example, this input would be processed and turned into the following input:

{
     "propertyOne": "Hi!",
     "proeprtyTwo":
}
{
    "propertyOne": "Hi!"
}
h1. Solution
Check if a key has been provided with a null value, and check if the key is optional. If it is optional, allow the value to pass through as null. If it is not optional, throw an error.

Under no circumstances, remove an expected key that was sent in the payload.

This PR is related to the yellitech/api pr: https://github.com/Yellitech/api/pull/279

2018-03-06 05:32 UTC, JoelSerjeant requested changes
Minor styling changes

2018-03-06 05:32 UTC, JoelSerjeant commented on src/Structr/Tree/Composite/MapNode.php
>                  if(array_key_exists($key, $value)) {
Styling, space between 'if' and '('

2018-03-06 05:32 UTC, JoelSerjeant commented on src/Structr/Tree/Composite/MapNode.php
> -                    if(NullNode::canHaveNullValue($value)) {
Styling, space between 'if' and '('

2018-03-06 06:40 UTC, JoelSerjeant approved these changes

2018-05-31 07:40 UTC, baspeeters approved these changes

2018-05-31 07:41 UTC, TUstenko approved these changes

2018-05-31 07:43 UTC, TUstenko commented
With a comment - I have doubts about the example:
{
     "propertyOne": "Hi!",
     "propertyTwo":
}
It's not correct json.

2018-08-21 14:06 UTC, merged